name: Repo Sync

on:
  workflow_dispatch:
  
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Repo-Sync.yaml'

  schedule:
    - cron: 15 * * * *

jobs:
 
  jd-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Bot
        run: |
          bash Scripts/Sync.sh \
            https://github.com/SuMaiKaDe/bot main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/JD-Bot
      - name: JDHelloWorld
        run: |
          bash Scripts/Sync.sh \
            https://github.com/JDHelloWorld/jd_scripts main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/jd-scripts ts2js

      - name: ZCY01
        run: |
          bash Scripts/Sync.sh \
            https://github.com/ZCY01/daily_scripts main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/ZCY01

      - name: airacg
        run: |
          bash Scripts/Sync.sh \
            https://github.com/airacg/jd_task main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/airacg
      - name: JD_Diy
        run: |
          bash Scripts/Sync.sh \
            https://github.com/chiupam/JD_Diy master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/JD-Diy
      - name: curtinlv
        run: |
          bash Scripts/Sync.sh \
            https://github.com/curtinlv/JD-Script main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/curtinlv

      - name: jiulan
        run: |
          bash Scripts/Sync.sh \
            https://github.com/jiulan/platypus main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/jiulan
      - name: star261
        run: |
          bash Scripts/Sync.sh \
            https://github.com/star261/jd main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/star261
      - name: smiek2121
        run: |
          bash Scripts/Sync.sh \
            https://github.com/smiek2121/scripts master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/smiek2121
      - name: X1a0He
        run: |
          bash Scripts/Sync.sh \
            https://github.com/X1a0He/jd_scripts_fixed main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/X1a0He
      - name: Aaron-lv
        run: |
          bash Scripts/Sync.sh \
            https://github.com/Aaron-lv/sync.git jd_scripts \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/Aaron-lv
      - name: 小埋
        run: |
          bash Scripts/Sync.sh \
            https://github.com/mmnvnmm/omo.git main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/omo
      - name: DDO
        run: |
          bash Scripts/Sync.sh \
            https://github.com/hyzaw/AllJDScripts master \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/DDO
      - name: Zero205
        run: |
          bash Scripts/Sync.sh \
            https://github.com/zero205/JD_tencent_scf main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/Zero205
      - name: 小埋bak1
        run: |
          bash Scripts/Sync.sh \
            https://github.com/DomaUmaruUMR/bak1.git main \
            https://${{ github.repository_owner }}:${{ secrets.ACTION_SECRET }}@github.com/smallfount/bak1
            
            
        
            
            
            
